title: Dave Cole
logo: "/images/logo.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  STEM and creative thinking enthusiast.
  <br><br>
  My current focus is on AI and cloud computing technologies.
  <br><br>
  <a href="https://www.linkedin.com/in/dave-cole-00145384/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
